---
- hosts: webservers
  become: yes
  tasks:
  - name: install java on ubuntu node
    apt:
      name: "{{ javaonubuntu }}"
      state: present
    when: ansible_os_family =="Debian"
  - name: install java on RedHat node
    yum:
      name: "{{ javaonRedHat }}"
      state: present
    when: ansible_os_family =="RedHat"  