---
- hosts: webservers
  become: yes
  tasks: 
  - name: install webserver on ubuntu14
    apt:
      name: "{{webserveronubuntu}}"
      state: present
    when: ansible_os_family =="Debian"
  - name: start webserver of ubuntu14
    service:
      name: "{{webserveronubuntu}}"
      state: started
    when: ansible_os_family =="Debian"
  - name: install webserver on RedHat
    yum:
      name: "{{webserveronRedHat}}"
      state: present
    when: ansible_os_family =="RedHat"
  - name: start webserver of RedHat
    service:
      name: "{{webserveronRedHat}}"
      state: started
    when: ansible_os_family =="RedHat"